version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "19:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: bundler
    versions:
    - "> 1.17"
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: async-websocket
    versions:
    - 0.16.0
    - 0.17.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.1
