require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "lib/templates/**/*"
    - "**/node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"

#
# Ruby Cops
#

Layout/CaseIndentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 35
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 250
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Naming/PredicateName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MutableConstant:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StructInheritance:
  Enabled: true
