require:
  - rubocop-performance

inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/main/rubocop/.rubocop-common.yml
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/main/rubocop/.rubocop-performance.yml

AllCops:
  TargetRubyVersion: 2.4 # this must match gemspec required_ruby_version

Naming/VariableNumber:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
